services:
    pg:
        image: postgres:16.3
        ports:
            - 5454:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: testDB
        restart: always
    redis:
        image: redis:7-alpine
        command: redis-server --loglevel warning
        ports:
            - "7001:6379"
        restart: always

volumes:
    pgdata:
        driver: local
    redis:
    node_modules:
